### ISSUE TITLE
Restarting main process?

### ISSUE THREAD

**Issue by Leooo** [schneems/puma_worker_killer#10]
Hello,

I may be missing someting totally obvious here, but:

This gem is great to mitigate memory leaks on applications using Puma. Though it only helps to restart workers, not to restart the main process when it is the one whose RAM is getting glutted.

Is this doable to restart the main process (and maybe all the workers at the same time then, not sure how it works) when this is the one consuming the most memory?

**Comment by evanphx** [comment]
In cluster mode, the master process never runs requests.

**Comment by Leooo** [comment]
Thanks for the confirmation! My initial doubt came from the fact that I am checking which worker is running  in my SSE thread using its index from the following line:

index=ObjectSpace.each_object(Puma::Cluster::Worker).map { |obj| obj }.first.try(:index)

but sometimes the index is empty, so I thought this may have been the master process.

L
