### ISSUE TITLE
Implications for long-running requests

### ISSUE THREAD

**Issue by julik** [schneems/puma_worker_killer#18]
I would like to try puma_worker_killer in my setup but I am using Puma to server very long requests (they sometimes span hours or even a couple of days). I cannot abort a running request mid-flight, so I need the killer to wait until the worker exhausts it's current requests, and take into account that this can take long.

Is the gem usable for this sort of use case?

**Comment by ruckus** [comment]
Good question. I'm looking at the source and its not clear if PWK will wait until a request finishes or it restarts it mid-flight. It *appears* that a request is killed mid-flight. 

But I'd love someone more knowledgeable to chime in. Thank you!

**Comment by schneems** [comment]
PWK sends TERM immediately, it's up to puma to do the right thing and clean up correctly

**Comment by julik** [comment]
That I do understand. The behavior after is defined by the somewhat-underdocumented `worker_shutdown_timeout`. However, if that timeout is set to a pretty large value, will PWK try a KILL too soon, or will it overreact and attempt more TERMs if the worker does not go away in a timely manner?

**Comment by schneems** [comment]
Everything we send will go through the puma interface. Right now we use `term` from Puma and it goes through it's paces. If we send the command multiple times to my knowledge puma doesn't have any kind of a counter or keep track of all of those "terms" and do something special if they hit some threshold.

**Comment by brauliobo** [comment]
> That I do understand. The behavior after is defined by the somewhat-underdocumented `worker_shutdown_timeout` in Puma proper (and afaik once a TERM is received the worker won't be receiving new requests). However, if that timeout is set to a pretty large value, will PWK try a KILL too soon, or will it overreact and attempt more TERMs if the worker does not go away in a timely manner?

just confirmed through the source code that it will send `KILL` after multiple `#term` calls and the `worker_shutdown_timeout` interval has passed
```ruby
      def term
        begin
          if @first_term_sent && (Time.now - @first_term_sent) > @options[:worker_shutdown_timeout]
            @signal = "KILL"
          else
            @term ||= true
            @first_term_sent ||= Time.now
          end
          Process.kill @signal, @pid if @pid
        rescue Errno::ESRCH
        end
      end
```
https://github.com/puma/puma/blob/edd2a1728e39d055545fd12ffdfa42d5d4ccbc58/lib/puma/cluster/worker_handle.rb#L75

so yes, it will interrupt nginx requests with the error `upstream prematurely closed connection while reading response header from upstream` as can be found in the error log

**Comment by brauliobo** [comment]
@schneems should I create a PR to document this scenario in the `README`?
