### ISSUE TITLE
JRuby fork not implemented issue

### ISSUE THREAD

**Issue by treble37** [schneems/puma_worker_killer#28]
1) In https://travis-ci.org/schneems/puma_worker_killer/jobs/112527114 there is:

`Error: test_rolling_restart(PumaWorkerKillerTest): NotImplementedError: fork is not available on this platform org/jruby/RubyKernel.java:1881:in `fork'`

which is due to *fork* not being implemented in JRuby.  (Edit: just noticed this is an allowed failure, but I'll leave this open because I'm also curious about #2 below)

2) Also, should Ruby 2.2 and 2.3 be added to the TravisCI tests? (mostly just a question for the author, I imagine Ruby 2.4.0dev, 2.2, and 2.3 are fairly similar).  Thanks.

**Comment by schneems** [comment]
This gem doesn't work with jruby because jruby doesn't implement fork

**Comment by schneems** [comment]
We should remove jruby and add 2.3 and 2.2
