### ISSUE TITLE
Where shall I start PumaWorkerKiller if I do not preload_app?

### ISSUE THREAD

**Issue by larryzhao** [schneems/puma_worker_killer#36]
Hi, 

I am trying to switch to `phase-restart`, so I removed `preload_app` and I found with this configuration, it seems that `PumaWorkerKiller` is not started wherever I put the `PumaWorkerKiller.start` ( tried in `before_fork`/`on_worker_boot`/`initializer`). Nothing reporting into `puma_stdout.log`.

Where should I start `PumaWorkerKiller` under this circumstance?

Thank you very much.

**Comment by schneems** [comment]
Closing in favor of #23
