### ISSUE TITLE
NoMethodError: undefined method `reaper_status_logs=' for PumaWorkerKiller:Module

### ISSUE THREAD

**Issue by vcardillo** [schneems/puma_worker_killer#44]
Using `config.reaper_status_logs = true` as per the docs, throws the following error:

```
[42188] ! Unable to load application: NoMethodError: undefined method `reaper_status_logs=' for PumaWorkerKiller:Module
```

Commenting this out of the config, solves the problem.

**Comment by schneems** [comment]
Please give me an app that reproduces the problem.

**Comment by vcardillo** [comment]
Unfortunately it's not open source software... are you not able to reproduce?

**Comment by daveallie** [comment]
Add [where_is](https://github.com/daveallie/where_is) to your Gemfile, and above your config block, can you please put `puts Where.are(PumaWorkerKiller, :config)` and paste the output back here.

Can you also replace `config.reaper_status_logs = true` with `puts config.reaper_status_logs` and paste your output back here.

**Comment by schneems** [comment]
Here's some instructions to help you generate a reproduction https://www.codetriage.com/example_app
