### ISSUE TITLE
Is there a way to specify a specific dyno that gets killed?

### ISSUE THREAD

**Issue by mberman84** [schneems/puma_worker_killer#52]
I have 10 or so separate queues with dynos in each that I'm using so I can allocate resources accordingly dependent on memory needs of each queue. I want to use puma worker killer to kill a dyno in a specific queue that goes above 98% memory usage. However, there doesn't seem to be a way to specify "only apply these puma killer settings to X worker/dyno/queue"

Is there a way to do that?

**Comment by schneems** [comment]
I don't totally understand. I don't recommend killing workers based on memory on Heroku, I recommend using rolling restarts instead.

Puma worker killer only works with web dynos i.e. running puma.
