### ISSUE TITLE
Need more clarity on some of the configurations

### ISSUE THREAD

**Issue by moustafasallam** [schneems/puma_worker_killer#67]
I need to have some clarity on some of the configuration that is written in the readMe file

```ruby
PumaWorkerKiller.rolling_restart_frequency = 12 * 3600 # 12 hours in seconds, or 12.hours if using Rails
```
If I am using PWK start not rolling_restart why should I set this in the configuration, what is the default or should I set it to `false` as mentioned.

**Comment by schneems** [comment]
> If I am using PWK start not rolling_restart why should I set this in the configuration, what is the default or should I set it to false as mentioned.

That example is showing ALL of the options available, you don't need to use anything you don't want. You can use rolling restarts along with the RAM killer if you want, or just one-or-the-
other.
