### ISSUE TITLE
Determine better ram default

### ISSUE THREAD

**Issue by freeformz** [schneems/puma_worker_killer#68]
FWIW, you can determine the amount of available RAM in MB in a Heroku Dyno (or probably any container that uses cgroups in which that cgroup data is exposed in the container) with:

Integer(Integer(IO.read("/sys/fs/cgroup/memory/memory.limit_in_bytes")) / 1024 / 1024)

The current amount of memory being used by *all* processes in a dyno can be found in `/sys/fs/cgroup/memory/memory.usage_in_bytes`. This is only currently exposed in private space dynos though.

**Comment by schneems** [comment]
oh, that’s useful.  Previously I’ve had to map “ulimit” results to different dyno types. This seems better.

**Comment by oyeanuj** [comment]
@schneems Just checking if this is on your radar to incorporate in this library? Thank you for creating this library!

**Comment by schneems** [comment]
@oyeanuj want to send me a PR?

**Comment by oyeanuj** [comment]
Unfortunately, I don't understand Heroku spaces or puma much to be able to PR this. Maybe @freeformz can?

**Comment by schneems** [comment]
On a standard-1 dyno:

```
~ $ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
536870912
```

and `536870912 / 1024 /1024 => 512` so it looks like this is right. I still want to make this the default, but also don't know when i'll have time to work on it.
