### ISSUE TITLE
Using RuboCop?

### ISSUE THREAD

**Issue by utkarsh2102** [schneems/puma_worker_killer#89]
Hi @schneems,

Thanks for your awesome work on this! 🔥 

However, whilst packaging this for Debian, we faced some issues. Would you be interested in using RuboCop here?
I'd be happy to raise a PR if so! 😄

**Comment by schneems** [comment]
I'm partial to `standard-rb` if you wanted to apply it to this project.

**Comment by schneems** [comment]
I merged a PR, we're now using rubocop

**Comment by utkarsh2102** [comment]
Ahaha, great, thanks!

**Comment by utkarsh2102** [comment]
Also, thanks for this quick fix! You're the best! ❤️ 
Though I have a couple of more things that I'd like to add here, should I raise another PR?
