### ISSUE TITLE
Dont kill PumaWorkerKiller when calling largest_worker.term a second time

### ISSUE THREAD

**Issue by Leooo** [schneems/puma_worker_killer#9]
Hello, I'm trying to use PumaWorkerKiller together with Rails ActionController::Live streaming.

Puma seems to have a problem restarting a worker if some SSEs connections are opened (even if the connections are on other workers see https://github.com/puma/puma/issues/569#issuecomment-68013757).

In any case, there may be some delay between the SIGTERM being sent to a worker by PumaWorkerKiller and the effective restart of the worker (if only to give time for the SSEs connections to close).

It seems PumaWorkerKiller gets killed (exception?) when sending a second time largest_worker.term in PumaWorkerKiller:: PumaMemory. I can get around the issue by testing if a restart order has already happened before largest_worker.term evaluates, and not sending the order again if that's the case.

**Comment by carljohnstone** [comment]
Hi, I've had practically the same problem - I've traced it back to `@options`  being undefined here - https://github.com/puma/puma/blob/master/lib/puma/cluster.rb#L86 - in older versions of puma, as long as you upgrade puma past v2.11.0 it's good.

**Comment by schneems** [comment]
Maybe we should bump the minimum version of puma in the gemspec?
